### ISSUE TITLE
Add POAP facet

### ISSUE THREAD

**Issue by youngancient** [youngancient/SonikDiamond#1]
- extend SonikDrop beyond ERC20 tokens but also allow claiming of ERC721 tokens

**Comment by youngancient** [comment]
The Facet would be an NFT contract, which a user can add in the token URI, the whitelist and etc.
It handles everything.

**Comment by Iam0TI** [comment]
> The Facet would be an NFT contract, which a user can add in the token URI, the whitelist and etc. It handles   

I think you can close this issue now  I push the code  [here](https://github.com/youngancient/SonikDiamond/pull/7)

**Comment by youngancient** [comment]
Great work man!
