### ISSUE TITLE
Check eligibility function

### ISSUE THREAD

**Issue by youngancient** [youngancient/SonikDiamond#4]
How do we check for the eligibility of a user without requiring the amount
    reason: most users won't know their allocations until they check
    Checking eligibility should then reveal their allocation

    view the check eligibility
    This function should check the eligibility and return (bool, uint256)

**Comment by Iam0TI** [comment]
we might need something like and oracle to return get the  amount . but for the bool true of false we can have second merkle root for just eligible addresses , but if we are going for the oracle you can do every offchain

**Comment by youngancient** [comment]
An oracle is not needed to get the amount. When I meant `amount`, it's the number of tokens they are getting. For more context, you can check the CheckEligibility function and the claim function in the SonikFacet.
A Merkle root for eligible addresses only, is a good idea. I thought about that too, but the main issue with this approach is after confirming that they are eligible, how do I get the amount of tokens to give them?

**Comment by Iam0TI** [comment]
> An oracle is not needed to get the amount. When I meant `amount`, it's the number of tokens they are getting. For more context, you can check the CheckEligibility function and the claim function in the SonikFacet. A Merkle root for eligible addresses only, is a good idea. I thought about that too, but the main issue with this approach is after confirming that they are eligible, how do I get the amount of tokens to give them?

let me do I will try and do research on it

**Comment by youngancient** [comment]
This issue will be handled asynchronously on the frontend while interfacing it with a simplex and secure server.
